### ISSUE TITLE
Fix code scanning alert - Use $(...) notation instead of legacy backticked ....

### ISSUE THREAD

**Issue by fayssalchokr** [fayssalchokr/fayssalOs#145]
Tracking issue for:
- [ ] https://github.com/fayssalchokr/fayssalOs/security/code-scanning/7

**Comment by emillyjcarlson** [comment]
deps=$(find /dir -name $(ls -1tr 201112[0-9][0-9]*.txt | tail -1l) -print)

**Comment by emillyjcarlson** [comment]
> Tracking issue for:
> 
> * [ ]  https://github.com/fayssalchokr/fayssalOs/security/code-scanning/7

deps=$(find /dir -name $(ls -1tr 201112[0-9][0-9]*.txt | tail -1l) -print)

**Comment by fayssalchokr** [comment]
closed by @emillyjcarlson

**Comment by emillyjcarlson** [comment]
> closed by @emillyjcarlson

@fayssalchokr
